// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Metric struct {
	ID         string           `json:"id"`
	SearchTerm string           `json:"search_term"`
	Count      int32            `json:"count"`
	PosterUrl  string           `json:"poster_url"`
	MovieID    string           `json:"movie_id"`
	Title      string           `json:"title"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
