// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
)

type Querier interface {
	CreateMetric(ctx context.Context, arg CreateMetricParams) (string, error)
	GetAllMetric(ctx context.Context) ([]GetAllMetricRow, error)
	GetMetricByTitle(ctx context.Context, title string) (Metric, error)
	UpdateMetric(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
